language: python
sudo: "required"
services:
  - docker
env:
  matrix:
    - OS=centos
      OS_VERSION=6
      PYTHON_VERSION=2
    - OS=centos
      OS_VERSION=7
      PYTHON_VERSION=2
    - OS=fedora
      OS_VERSION=26
      PYTHON_VERSION=2
    - OS=fedora
      OS_VERSION=27
      PYTHON_VERSION=2
    - OS=fedora
      OS_VERSION=rawhide
      PYTHON_VERSION=2
script:
 - pip install coveralls
 - ./test.sh
after_success: coveralls
notifications:
  email: false
